build:
  image: library/node:argon
  pull: true
  commands:
    - git --version
    - node --version
    - npm --version
    - npm install --silent
    - npm test -- --silent || npm test
cache:
  mount:
    - node_modules
    - .git
branches:
  - master
  - develop
