language: node_js
git:
  depth: 10
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  - "iojs-v1.0.4"
cache:
  bundler: true
  apt: true
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f5350a3bccfdf3d07867
sudo: false
branches:
  only:
    - compatibleTest
